#!/bin/bash

source script/test_helper

main() {
  start_server
  (cd src &&
    ghc --make Main.hs -fforce-recomp -fhpc -o SpecRunner && ./SpecRunner)
  (cd src &&
    hpc markup SpecRunner)
  kill_server
  script/clean-build
  open src/hpc_index.html
}

main
