#!/bin/bash

source script/test_helper

main() {
  start_server
  ghc --make Network/Kafka/Main.hs -fforce-recomp -fhpc -o Network/Kafka/SpecRunner && ./Network/Kafka/SpecRunner
  hpc markup SpecRunner
  kill_server
  script/clean-build
  open hpc_index.html
}

main
