#!/bin/bash

set -e

if [ $# -ne 0 ]; then
  echo "" | ghci -Wall -fwarn-tabs -fno-warn-missing-signatures -fno-warn-type-defaults -Werror -v0 $1
  hlint $1
else
  echo "" | ghci -Wall -fwarn-tabs -fno-warn-missing-signatures -fno-warn-type-defaults -Werror -v0 src/*.hs
  find src -name "*.hs" | xargs hlint
fi

