#!/bin/bash

set -e

(cd src &&
  ghc --make -O2 -o ./perf Bench/Main.hs)

trim() {
  sed 's/ *$//g'
}

find_mean() {
  grep 'mean:' | cut -d ':' -f 2 | cut -d ',' -f 1 | trim
}

produce10() {
  echo "`(cd src && ./perf produce/10p | find_mean)`" 
}

produce100() {
  echo "`(cd src && ./perf produce/100p | find_mean)`" 
}

consume10() {
  echo "`(cd src && ./perf consume/10c | find_mean)`"
}

consume100() {
  echo "`(cd src && ./perf consume/100c | find_mean)`"
}

# Get the hash
hash="`git log -1 --pretty=%h`"

echo "hash, produce-10-mean, produce-100-mean, consume-10-mean, consume-100-mean"
echo "$hash,`produce10`,`produce100`,`consume10`,`consume100`"
