#!/bin/bash

source script/test_helper

set -e

(cd src &&
  ghc --make -O2 -o ./perf Bench/Main.hs)

trim() {
  sed 's/ *$//g'
}

find_mean() {
  grep 'mean:' | cut -d ':' -f 2 | cut -d ',' -f 1 | trim
}

produce10() {
  echo "`(cd src && ./perf produce/10p | find_mean)`" 
}

produce100() {
  echo "`(cd src && ./perf produce/100p | find_mean)`" 
}

consume10() {
  echo "`(cd src && ./perf consume/10c | find_mean)`"
}

consume100() {
  echo "`(cd src && ./perf consume/100c | find_mean)`"
}

roundtripBasicConsumer() {
  (start_server)
  result=$(echo "`(cd src && ./perf consumerRoundTrip/roundtripBasicConsumer | find_mean)`")
  kill_server
  echo "$result"
}

roundtripKeepAliveConsumer() {
  (start_server)
  result=$(echo "`(cd src && ./perf consumerRoundTrip/roundtripKeepAliveConsumer | find_mean)`")
  kill_server
  echo "$result"
}

roundtripBasicProducer() {
  (start_server)
  result=$(echo "`(cd src && ./perf producerRoundTrip/roundtripBasicProducer | find_mean)`")
  kill_server
  echo "$result"
}

roundtripKeepAliveProducer() {
  (start_server)
  result=$(echo "`(cd src && ./perf producerRoundTrip/roundtripKeepAliveProducer | find_mean)`")
  kill_server
  echo "$result"
}

# Get the hash
hash="`git log -1 --pretty=%h`"

echo "hash, produce-10-mean, produce-100-mean, consume-10-mean, consume-100-mean, roundtripBasicConsumer-mean, roundtripKeepAliveConsumer-mean, roundtripBasicProducer-mean, roundtripKeepAliveProducer-mean"
echo "$hash,`produce10`,`produce100`,`consume10`,`consume100`,`roundtripBasicConsumer`, `roundtripKeepAliveConsumer`, `roundtripBasicProducer`, `roundtripKeepAliveProducer`"
