#!/bin/bash

source script/test_helper

main() {
  ghc --make Network/Kafka/Profiling/Main.hs -fforce-recomp -prof -auto-all -caf-all -O2 -rtsopts -o ./Network/Kafka/profiled
  (start_server)
  ./Network/Kafka/profiled +RTS -P
  kill_server
  script/clean-build > /dev/null 2>&1
}

main
