#!/bin/bash

start_server() {
    cd kafka/kafka
    bin/kafka-server-start.sh config/server.properties > /dev/null 2>&1 &
}

wait_for_server() {
    while true; do
        lsof -i :9092 > /dev/null
        if [[ $? == 0 ]]; then
            break
        fi
    done
}

wait_for_server_stop() {
    while true; do
        lsof -i :9092 > /dev/null
        if [[ $? != 0 ]]; then
            break
        fi
    done
}

