#!/bin/bash
source script/test_helper

main () {
  (cd /tmp/kafka-logs && ls | xargs rm -r)
  (start_server)
  wait_for_server
  pid=$(echo "`lsof -i :9092 | tail -1 | cut -d ' ' -f 5`")
  script/build &&
    (cd src &&
      ./SpecRunner +RTS -N4)
  kill -9 $pid
  (cd kafka/kafka && bin/kafka-server-stop.sh)
  wait_for_server_stop
  (cd /tmp/kafka-logs && ls | xargs rm -r)
}

main
