#!/bin/bash

ensure_empty_logs_dir() {
  (cd /tmp/kafka-logs && ls | xargs rm -r)
}

start_server() {
  ensure_empty_logs_dir
  (cd kafka/kafka &&
    bin/kafka-server-start.sh config/server.properties > /dev/null 2>&1 &)
  wait_for_server
}

wait_for_server() {
    while true; do
        lsof -i :9092 > /dev/null
        if [[ $? == 0 ]]; then
            break
        fi
    done
}

wait_for_server_stop() {
    while true; do
        lsof -i :9092 > /dev/null
        if [[ $? != 0 ]]; then
            break
        fi
    done
}

find_server() {
  echo "`lsof -i :9092 | tail -1 | cut -d ' ' -f 5`"
}

kill_server() {
  pid=$(find_server)
  kill -9 $pid
  (cd kafka/kafka && bin/kafka-server-stop.sh)
  wait_for_server_stop
  ensure_empty_logs_dir
}

